#!/usr/bin/env bash

set -e

source "$(git --exec-path)/git-sh-setup"

# Generate a portable in-place sed "variable".
case $(uname -s) in
*Linux*)
    IN_PLACE_SED="sed -i" ;;
*)
    IN_PLACE_SED="sed -i ''" ;;
esac

is_merge() {
    test -n "$(git rev-list -1 --merges $1~1..$1)"
}

# Go to top level
cd_to_toplevel

# Only if we are clean
require_clean_work_tree $cmd

for ((iter=0;iter<${1:-1};iter++)); do
    # Not if this is a merge commit.
    is_merge "HEAD" && die "HEAD is a merge commit, which is unsupported"

    # Not if we are in a non-interactive rebase
    test -d ".git/rebase-apply" && die "Non-interactive rebase is unsupported"

    # If we're not in an interactive rebase, there's no next commit
    if ! test -d ".git/rebase-merge"; then
        echo "At top"
        exit
    fi

    # Ensure the next commit is an edit.
    # If this fails, print the result.
    if ! errtext=$(GIT_SEQUENCE_EDITOR="$IN_PLACE_SED '1 s/^[a-z]\{1,\}/edit/'" git rebase --edit-todo 2>&1); then
        echo "$errtext" 1>&2
        die
    fi

    # Go to next commit.
    if ! errtext=$(git rebase --continue 2>&1); then
        echo "$errtext" 1>&2
        die
    fi

    echo HEAD is now at "$(git log --format='%h %s' -n 1 HEAD)"
done
